services:
  # Application Service — Peminjaman Service (IAE Tugas 2)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peminjaman-service
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_NAME=Peminjaman-Service
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - IAE_API_KEY=102022400314
      - L5_SWAGGER_GENERATE_ALWAYS=true
      - KEANGGOTAAN_SERVICE_URL=http://host.docker.internal:8001
    networks:
      - peminjaman-network


networks:
  peminjaman-network:
    driver: bridge
